BOOTMAGIC_ENABLE = no       	# Enable Bootmagic Lite
MOUSEKEY_ENABLE = no        	# Mouse keys
EXTRAKEY_ENABLE = yes        	# Audio control and System control
NKRO_ENABLE = no				# hz
BACKLIGHT_ENABLE = no       	# Enable keyboard backlight functionality
AUDIO_ENABLE = no           	# Audio output
RGBLIGHT_ENABLE = no       		# Enable WS2812 RGB underlight.
SWAP_HANDS_ENABLE = no      	# Enable one-hand typing
OLED_ENABLE = no				# hz